// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbls51Z7feOVwxsf_6plqj3htKo_9Y2s8',
    appId: '1:1090453038447:android:f77090e4fbd76d7afaf49a',
    messagingSenderId: '1090453038447',
    projectId: 'the-movie-app-tmdb-d109d',
    storageBucket: 'the-movie-app-tmdb-d109d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvZw23WW1vLRuKh0t2W70qGzXy9ejZVmU',
    appId: '1:1090453038447:ios:6f99efc976e757ccfaf49a',
    messagingSenderId: '1090453038447',
    projectId: 'the-movie-app-tmdb-d109d',
    storageBucket: 'the-movie-app-tmdb-d109d.appspot.com',
    iosClientId: '1090453038447-brnqudvcrf0nohkc5rgv5m0c5ner7ras.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
